export const treeViewerContainer: string;
export const showTreePanel: string;
export const hideTreePanel: string;
export const viewerMenuContainer: string;
export const assessmentPanel: string;
export const showAssessmentPanel: string;
export const hideAssessmentPanel: string;
export const conditionTextBox: string;
export const radingConditionCell: string;
